# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7956d16a53054d5d84514e1787cadd04b0311a58de260efcbcd574c1716ed5c3e7a0ef6b43fbe62af546d0e33b21b27269908d6b3839ae79aa7c19d8ca4e3132

test:
  secret_key_base: 249203c11c533ed5ecc55264684c0b1ccd435897d868db1b4eba7e3623ae6d9ce3c6bb10a047e9450b8d78c373ee4aadfddc68a8162992113dc0da3c15f8d403

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
